{% set name = "jarvis-leaderboard" %}
{% set version = "2024.10.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/usnistgov/jarvis_leaderboard/archive/refs/tags/v{{ version }}.tar.gz

  sha256: 985f6238371df7b5c9215d099e0e7d9e2e01b2fd95acaa839408e9d9e8fc88e4

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools'
    - pip
  run:
    - python >=3.8
    - numpy >=1.19.5
    - scipy >=1.6.3
    - jarvis-tools >=2021.07.19
    - scikit-learn >=0.24.1
    - pandas >=1.2.4
    - mkdocs =1.5.3
    - mkdocs-material ==9.5.14
    - pydantic >=1.8.1
    - markdown ==3.2.1
    - absl-py ==1.4.0
    - nltk >=3.8.1
    - rouge
    - pymatgen
    - lammps
    - gpaw
    # - abinit
    # - abipy
    - alignn
    - qe
    - atomman
    # - rouge-score ==0.1.2
    # - absl-py ==1.4.0
    # - evaluate ==0.4.0
    # - mkdocs >=1.6.0
    # - mkdocs-material >=9.0.5  

test:
  requires:
    - pip
    - pytest
  imports:
    - jarvis_leaderboard
    - jarvis_leaderboard.rebuild
  commands:
    - pip check
    # - python -c "from jarvis_leaderboard.rebuild import rebuild_pages; rebuild_pages()"



about:
  home: https://github.com/usnistgov/jarvis_leaderboard
  summary: jarvis_leaderboard
  license: NIST-PD
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - knc6
    - jan-janssen
