{% set name = "jarvis-leaderboard" %}
{% set version = "2024.4.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/usnistgov/jarvis_leaderboard/archive/refs/tags/v{{ version }}.tar.gz 
  
  sha256: 6efddeba5a5f3921957f9022e17e0bf374d787104ddf42e54cf6cf9c65b5ce2b

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.19.5
    - scipy >=1.6.3
    - jarvis-tools >=2021.07.19
    - scikit-learn >=0.24.1
    - pandas >=1.2.4
    # - mkdocs >=1.6.0
    # - mkdocs-material >=9.0.5
    - mkdocs =1.5.3
    - mkdocs-material ==9.5.14
    - pydantic >=1.8.1
    - markdown ==3.2.1
    # - absl-py ==1.4.0
    # - evaluate ==0.4.0
    - nltk ==3.8.1
    # - rouge-score ==0.1.2
    - rouge
    - pymatgen

test:
  imports:
    - jarvis_leaderboard
    - jarvis_leaderboard.rebuild
    # - jarvis_leaderboard.rebuild.rebuild_pages
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/usnistgov/jarvis_leaderboard
  summary: jarvis_leaderboard
  license: NIST-PD
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - knc6
    - jan-janssen
