{% set name = "jarvis-leaderboard" %}
{% set version = "2023.7.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jarvis_leaderboard-{{ version }}.tar.gz
  sha256: 4786873d86ee2d9c1e9dfea48768c66f8668258c11340dc0a9953caa67ee73e0

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.19.5
    - scipy >=1.6.3
    - jarvis-tools >=2021.07.19
    - scikit-learn >=0.24.1
    - pandas >=1.2.4
    - mkdocs-material >=9.0.5
    - pydantic >=1.8.1
    - markdown ==3.2.1
    - absl-py ==1.4.0
    - evaluate ==0.4.0
    - nltk ==3.8.1
    - rouge-score ==0.1.2

test:
  imports:
    - jarvis_leaderboard
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/knc6/jarvis_leaderboard
  summary: jarvis_leaderboard
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - knc6
    - jan-janssen
